"""
📄 Report Generator Module
Generates Research Papers, Blog Posts, and HTML Slides using LLM.
"""

import os
from typing import Dict, List
from datetime import datetime
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()


class ReportGenerator:
    """
    Generates different output formats from research data:
    - Research Paper (Markdown)
    - Blog Post (Markdown)
    - Presentation Slides (HTML with Reveal.js)
    """

    def __init__(self):
        self.use_ollama = os.getenv("USE_OLLAMA", "false").lower() == "true"
        if self.use_ollama:
            self.client = OpenAI(
                base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1"),
                api_key="ollama"
            )
            self.model = os.getenv("OLLAMA_MODEL", "llama3.2")
        else:
            self.client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
            self.model = os.getenv("OPENAI_MODEL", "gpt-4o-mini")

    def generate(self, context: Dict, output_format: str) -> str:
        """
        Generate output in the specified format.

        Args:
            context: Dict containing topic, summaries, synthesis, articles, etc.
            output_format: 'report' | 'blog' | 'slides'

        Returns:
            Generated content as string
        """
        generators = {
            "report": self._generate_report,
            "blog": self._generate_blog,
            "slides": self._generate_slides,
        }
        generator = generators.get(output_format, self._generate_report)
        return generator(context)

    def _generate_report(self, context: Dict) -> str:
        """Generate a formal research paper in Markdown."""
        topic = context["topic"]
        synthesis = context.get("synthesis", "")
        articles = context.get("articles", [])
        timestamp = context.get("timestamp", datetime.now().isoformat())

        # Build sources section
        sources_md = "\n".join([
            f"{i+1}. [{a.get('title', 'Unknown')}]({a.get('url', '#')}) — {a.get('domain', '')}"
            for i, a in enumerate(articles)
        ])

        prompt = f"""Write a comprehensive, formal research paper about: "{topic}"

Based on this research synthesis:
{synthesis[:4000]}

Format as a professional academic research paper in Markdown with these sections:
# {topic} - Research Report

## Abstract
(2-3 sentence summary)

## 1. Introduction
(Background, why this topic matters, research objectives)

## 2. Methodology
(How this research was conducted - web search, article analysis, synthesis)

## 3. Key Findings
(Major discoveries organized by theme, with specific data points)

## 4. Analysis & Discussion
(Deeper analysis, implications, comparisons)

## 5. Conclusions
(Summary of main points, significance)

## 6. Future Research Directions
(What could be explored further)

## References
{sources_md}

---
*Generated by Autonomous Research Agent | {timestamp[:10]}*

Write in professional academic English. Be specific and data-driven. Minimum 800 words."""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are an expert academic researcher and writer. Write comprehensive, well-structured research papers."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=3000,
                temperature=0.5
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            return f"# {topic} - Research Report\n\n*Error generating report: {e}*\n\n## Research Synthesis\n\n{synthesis}"

    def _generate_blog(self, context: Dict) -> str:
        """Generate an engaging blog post in Markdown."""
        topic = context["topic"]
        synthesis = context.get("synthesis", "")
        articles = context.get("articles", [])
        timestamp = context.get("timestamp", datetime.now().isoformat())

        sources_md = "\n".join([
            f"- [{a.get('title', 'Unknown')}]({a.get('url', '#')})"
            for a in articles[:5]
        ])

        prompt = f"""Write an engaging, informative blog post about: "{topic}"

Based on this research:
{synthesis[:4000]}

Format as a compelling blog post in Markdown:
- Start with a catchy hook/introduction
- Use headers (##) to organize sections
- Include interesting facts, stats, and insights
- Use bullet points and bold text for readability
- Write in an accessible but authoritative tone
- 600-900 words total
- End with a conclusion that ties everything together

Include a "Further Reading" section:
{sources_md}

---
*Research by Autonomous Research Agent | {timestamp[:10]}*"""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are an expert content writer who creates engaging, well-researched blog posts."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=2000,
                temperature=0.6
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            return f"# {topic}\n\n*Error generating blog: {e}*\n\n{synthesis}"

    def _generate_slides(self, context: Dict) -> str:
        """Generate an HTML presentation using Reveal.js."""
        topic = context["topic"]
        synthesis = context.get("synthesis", "")
        articles = context.get("articles", [])
        timestamp = context.get("timestamp", datetime.now().isoformat())

        prompt = f"""Create content for a presentation about: "{topic}"

Based on this research:
{synthesis[:3000]}

Generate exactly 8 slides in this JSON format:
[
  {{"title": "slide title", "bullets": ["point 1", "point 2", "point 3"], "type": "title"}},
  ...
]

Slide types: title (first slide), content, findings, analysis, conclusion
Each slide should have 3-5 concise bullet points.
Make it impactful and data-driven."""

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You are a presentation expert. Return ONLY valid JSON array."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=1500,
                temperature=0.4
            )
            import json
            import re
            raw = response.choices[0].message.content.strip()
            # Extract JSON
            json_match = re.search(r'\[.*\]', raw, re.DOTALL)
            if json_match:
                slides_data = json.loads(json_match.group())
            else:
                raise ValueError("No JSON found")
        except Exception:
            # Fallback slides
            slides_data = [
                {"title": topic, "bullets": ["Autonomous Research Report", f"Sources: {len(articles)}", timestamp[:10]], "type": "title"},
                {"title": "Overview", "bullets": ["Research conducted autonomously", "Multiple sources analyzed", "Key insights extracted"], "type": "content"},
                {"title": "Key Findings", "bullets": synthesis.split("\n")[:4] if synthesis else ["See full report"], "type": "findings"},
            ]

        return self._build_html_slides(topic, slides_data, timestamp)

    def _build_html_slides(self, topic: str, slides: List[Dict], timestamp: str) -> str:
        """Build Reveal.js HTML presentation."""
        slides_html = ""
        colors = ["#1a1a2e", "#16213e", "#0f3460", "#533483", "#e94560"]

        for i, slide in enumerate(slides):
            color = colors[i % len(colors)]
            title = slide.get("title", "")
            bullets = slide.get("bullets", [])
            bullets_html = "".join([f"<li>{b}</li>" for b in bullets])
            slide_type = slide.get("type", "content")

            if slide_type == "title":
                slides_html += f"""
        <section data-background="{color}">
            <h1 style="font-size:2em;color:#fff;">{title}</h1>
            <ul style="list-style:none;color:#ccc;">{bullets_html}</ul>
            <p style="color:#888;font-size:0.7em;margin-top:2em;">Autonomous Research Agent</p>
        </section>"""
            else:
                slides_html += f"""
        <section data-background="{color}">
            <h2 style="color:#ffd700;">{title}</h2>
            <ul style="color:#fff;font-size:0.85em;line-height:1.8;">{bullets_html}</ul>
        </section>"""

        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{topic} - Research Presentation</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4/dist/reveal.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reveal.js@4/dist/theme/night.css">
    <style>
        .reveal ul li {{ margin: 0.4em 0; }}
        .reveal h1, .reveal h2 {{ text-transform: none; }}
    </style>
</head>
<body>
    <div class="reveal">
        <div class="slides">
            {slides_html}
            <section data-background="#1a1a2e">
                <h2 style="color:#ffd700;">Thank You</h2>
                <p style="color:#ccc;">Research generated autonomously</p>
                <p style="color:#888;font-size:0.7em;">{timestamp[:10]}</p>
            </section>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/reveal.js@4/dist/reveal.js"></script>
    <script>Reveal.initialize({{hash: true, transition: 'slide'}});</script>
</body>
</html>"""
